project_name: germanium

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/germanium
    binary: germanium
    ldflags:
      - -s -w
      - -X github.com/matsuyoshi30/germanium/cli.version={{.Version}}
      - -X github.com/matsuyoshi30/germanium/cli.commit={{.ShortCommit}}
      - -X github.com/matsuyoshi30/germanium/cli.date={{.Date}}

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: x86_64
    files:
      - LICENSE
      - CREDITS

release:
  prerelease: auto

changelog:
  skip: true
